### ISSUE TITLE
Can the default arg on command be moved into the config map

### ISSUE THREAD

**Issue by juliostanley** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#102]
Hi

Could you move the statefulset `command` into the configmap just like the other scripts?

https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/ca0bfcb8dcc7a5c4439cb42779c43c89f839499e/pubsubplus/templates/solaceStatefulSet.yaml#L119

The reason is that when translating the template to terraform tf and using `<<-EOF`, it gets applied to kubernetes as `>+` however, somehow this causes solace to not complete boot up (stops at restarting syslog).

To keep similarity, maybe it could change to:
```yaml
comand:
- bash
- "-ec"
- "source ./<new-script-path>"
```

P.S.
Yes, it is possible to modify the tf to move the command into the configmap scripts, however it would be preferred to perform an auto translation from helm to tf (currentley not possible because of the auto created <<-EOF)

**Comment by bczoma** [comment]
Hi @juliostanley, so we can investigate and better understand, are you using the Terraform Helm provider https://registry.terraform.io/providers/hashicorp/helm/latest/docs ?

**Comment by bczoma** [comment]
Is this still relevant? Suggesting to close it

**Comment by juliostanley** [comment]
We can close this.

Instead of the terraform helm provider we were rendering the templates and using tfk8s to translate them to .tf, we are no longer using this translation mechanism.
