### ISSUE TITLE
Issue in failover

### ISSUE THREAD

**Issue by shukla2009** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#103]
This helm run all 3 nodes [Primary,Backup,Monitor] as one statefulset,
I have observed the behavior if in any scenario 
Solace-0[Primary] ImagePullBack
Solace-1[Backup] Running [Not Ready]
Solace-2[Monitor] Running [Not Ready]

All goes down and some for any reason only Solace-1 and Solace-2 came up.. 
Solace-2 keep on waiting for leader and Solace-1 not able to figure out the config sync, Even STS restart doen't help as its restart nodes in order 2->1->0 

I forcefully killed pods multiple time till my issue gone but end up loosing cluster information , though vpn configuration is intact

**Comment by bczoma** [comment]
https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/pull/109 has pushed improvements.
I suggest closing this.
