### ISSUE TITLE
[Enhancement] Add extraEnv parameters to helm chart

### ISSUE THREAD

**Issue by JanGrosse** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#106]
Hello everyone, 
we are currently using the helm charts to deploy our Solace Brokers into our OpenShift environment.

We have the use case to configure our Brokers for writing all their logs not only into the specified files but also to stdout.
(https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Docker-Tasks/Configuring-VMR-Container-Logging.htm)

For that we are setting the configuration keys as environment variables for the StatefulSets. This is working but has to be done manually as of now. The idea would be to have a seperate field in the values.yml called e.g. extraEnvs where one can specifiy additional environment variables for the container. 

So, in the values.yml 
```
[...]
## Additional solace container environment variable
extraEnv: {}
[...]
```

And in the solaceStatefulSet.yml
```
[...]
        env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        - name: STATEFULSET_NAME
          value: {{ template "solace.fullname" . }}
[...]
```

**Comment by bczoma** [comment]
Support has been added by https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/pull/109 
This can now be closed.
