### ISSUE TITLE
Last retained message is not delivered to a newly connected subscriber

### ISSUE THREAD

**Issue by deepavk** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#108]
I'm testing a setup with a publisher and 2 subscribers using the solace broker which is deployed on a kubernetes cluster. using the helm chart available here:
https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart 

The publisher is started and messages are being sent with the retain value set to true. The subscriber is not online at this time.

The subscriber establishes a new connection with the subscriber Qos parameter set to 1 and clean session set to false.
The subscriber doesn't receive the last published message even though the retain value at publisher was set to true. 

Thanks, 
Deepa

**Comment by KenBarr** [comment]
Hi Deepa

Thanks for trying Solace.

This type of question is better suited for Solace Community:  https://solace.community/

From Solace Documentation,  I believe you need to configure retain including adding a retain cache: 
https://docs.solace.com/Open-APIs-Protocols/MQTT/Using-MQTT.htm

"Retained Messages
Retained messages are used when publishers send state messages on an irregular and/or infrequent basis. Published messages which have their retain bit set are stored by the Solace messaging network and delivered to subscribing clients when they subscribe to a topic that matches the retained message’s published topic. This allows subscribers to be notified immediately of the most recent state upon subscribing.

For more information about configuring Solace PubSub+ event brokers to support retained messages, see Managing MQTT Retained Messages.

Support for MQTT Retained Messages is a Controlled Availability (CA) feature. Please contact Solace to find out if this feature is supported for your use case.

MQTT Retain Caches
In Solace PubSub+ event brokers, retained messages are preserved in special Cache Clusters called MQTT retain caches. In other words, Solace PubSub+ Cache is the underlying mechanism used to store, manage, and select which retained messages to publish as clients add topic filters."

**Comment by deepavk** [comment]
Hi @KenBarr 

Thank you for the information. I will contact Solace to find more details about this feature for the specific usecase
