### ISSUE TITLE
[BUG] Helm error with custom service annotation

### ISSUE THREAD

**Issue by mivalsten** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#112]
When trying to deploy Solace Pub Sub as internally loadbalanced service, I get following error:

```
PS > helm upgrade solace-pubsub solacecharts/pubsubplus -f .\values.yml --set service.annotation."service.beta.kubernetes.io/azure-load-balancer-internal"=true
Error: UPGRADE FAILED: YAML parse error on pubsubplus/templates/service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field .metadata.annotations of type map[string]string
PS > helm upgrade solace-pubsub solacecharts/pubsubplus -f .\values.yml
Error: UPGRADE FAILED: YAML parse error on pubsubplus/templates/service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field .metadata.annotations of type map[string]string
```

content of values.yml
```
service:
  type: LoadBalancer
  annotations: 'service.beta.kubernetes.io/azure-load-balancer-internal: "true"'
```

I think that this value should be an object, not a string.

**Comment by bczoma** [comment]
Thank you @mivalsten for raising this and the contribution, I'm working on updates and will take your input.
Regards:
Balazs

**Comment by mivalsten** [comment]
Do you have an ETA on the updates? I'm planning to deploy Solace PubSub to production environment in around two weeks, and would prefer to deploy from official helm chart.

**Comment by bczoma** [comment]
It may be tight for mid-May and it is not entirely in my control. I'll look at all options including your suggestion and will notify you where it settled so you can have at least the proposed code by the time of your deployment or earlier.

**Comment by PhilippeKhalife** [comment]
Fixed
