### ISSUE TITLE
Solace config-keys do not support "-"

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#12]
Reference: [RT27310](https://rt.solace.com/rt/Ticket/Display.html?id=27310)

Workaround in place:
  REmove "-" from routernames before cofiguring redundancy via config keys.

This workaround should be removed once issue resolved.

**Comment by bczoma** [comment]
Closing this as there is no plan to implement this on the broker. So the workaround will stay.
