### ISSUE TITLE
pubsubplus-dev helm chart file not found

### ISSUE THREAD

**Issue by WellsCui** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#123]
## Description

The helm chart repo was changed from `https://solaceproducts.github.io//pubsubplus-kubernetes-quickstart/helm-charts` to `https://solaceproducts.github.io/pubsubplus-kubernetes-helm-quickstart/helm-charts` recently. However, the link of `pubsubplus-dev` chart file did not change. It still is `https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz`. It should be `https://solaceproducts.github.io/pubsubplus-kubernetes-helm-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz`

Here is the error:
`
Downloading pubsubplus-dev from repo https://solaceproducts.github.io/pubsubplus-kubernetes-helm-quickstart/helm-charts
Save error occurred:  could not download https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz: failed to fetch https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz : 404 Not Found
Error: could not download https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz: failed to fetch https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/helm-charts/pubsubplus-dev-3.2.0.tgz : 404 Not Found
`

PS: the document needs to be updated as well: https://artifacthub.io/packages/helm/solace/pubsubplus-dev

**Comment by bczoma** [comment]
This should be now resolved. Thank you @WellsCui for raising this, please open a new issue if there is still any related problem you see. Closing.
