### ISSUE TITLE
login directory missing inside Solace pubsubplus pod

### ISSUE THREAD

**Issue by ayaan604** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#130]
I installed solacepubsubplus in my Kubernetes cluster using the provided helm chart, and my solace pod came into running state as well. It has a service with multiple nodeports, out of which I used the nodeport targetting the login page port (8080). I got '404 not found' error on browser and this in solace pod logs

"2023/06/16 12:59:56 [error] 558#558: *174 open() "/usr/sw/loads/currentload/www/login" failed (2: No such file or directory), client: 10.244.0.0, server: , request: "GET /login HTTP/1.1", host: ":32754""

How do I create login page for solace? Or should it have been there by default and there is something wrong with the installation.

I tried creating login directory through solace CLI but was unable to.

**Comment by bczoma** [comment]
Hi @ayaan604 , the login page (WebUI) should have been there by default. Wondering if the node through which you were trying is accessible?
Also double check the nodeport assigned to the `tcp-semp` port mapping by running e.g.:
```
echo -e "\nProtocol\tAddress\n"`kubectl get svc --namespace default test-pubsubplus -o jsonpath="{range .spec.ports[*]}{.name}\t<NodeIP>:{.nodePort}\n"`
```

**Comment by bczoma** [comment]
Also, if you were trying to login from the local private k8s network and pod address then 8080 is the port to use.

**Comment by ayaan604** [comment]
Hi Balazs, 
No I was not accessing using pod address, I was trying to access it through the IP address of master node of K8s cluster, and the nodeport I am using is of tcp-semp indeed. So I am not able to detect any common mistake from my side.
I would like to mention that when I installed the helm chart, the pods did not start because the helm chart only had PVC for solace, but I had to manually create and bound a PV to that PVC. After that the pod changed from pending state to running state, however this error is just persisting 

Can you confirm if this directory "/usr/sw/loads/currentload/www/login" exists by default, or do I have to do something to create it? Thanks for the reply though, and I would really appreciate your further support. 

Output of the command that you sent:
tcp-ssh <NodeIP>:31248
tcp-semp        <NodeIP>:31454
tls-semp        <NodeIP>:32377
tcp-smf <NodeIP>:31397
tcp-smfcomp     <NodeIP>:32563
tls-smf <NodeIP>:31712
tcp-smfroute    <NodeIP>:31082
tcp-web <NodeIP>:31201
tls-web <NodeIP>:30042
tcp-rest        <NodeIP>:31768
tls-rest        <NodeIP>:30573
tcp-amqp        <NodeIP>:30172
tls-amqp        <NodeIP>:31985
tcp-mqtt        <NodeIP>:30439
tls-mqtt        <NodeIP>:31710
tcp-mqttweb     <NodeIP>:30300
tls-mqttweb     <NodeIP>:31774

I was using the 31454 port.
  
![image](https://github.com/SolaceProducts/pubsubplus-kubernetes-helm-quickstart/assets/81520452/1a1339e4-baca-44b9-b931-ddb72e850e41)

**Comment by ayaan604** [comment]
![image](https://github.com/SolaceProducts/pubsubplus-kubernetes-helm-quickstart/assets/81520452/6dfb8db1-b018-44d0-b6d2-0153dc718534)

Let me know if this gives you any insights, or if I need to pull some more logs.

**Comment by bczoma** [comment]
It looks like there is an issue with volume permissions or securityContext rather than with network access to the management port. Is this a standard deployment following the [steps in the QuickStart](https://github.com/SolaceProducts/pubsubplus-kubernetes-helm-quickstart#3-install-the-solace-pubsub-software-event-broker-with-default-configuration)?

**Comment by ayaan604** [comment]
Helm chart I downloaded from https://artifacthub.io/packages/helm/solace/pubsubplus
And yes standard deployment, only changed value of solace admin password in values.yaml.

However as I mentioned previously, Solace pod was in pending state after helm install, because the PVC in the helm chart had no PV to be bound to. So I manually created a PV and bind it to the PVC. Should I not have done that? Can you please suggest me how else I should deal with unbound PVC. Thanks

**Comment by bczoma** [comment]
The issue is likely that the broker container does not have permissions for R/W access the directories in the mounted volume. We have found that `hostPath` has such issues. Which type are you using?

You can check if this is the issue by creating another deployment with `storage.persistent=false` setting. This is using ephemeral volumes for testing.

**Comment by ayaan604** [comment]
I did storage.persistent=false inside values.yaml. It did not create pvc after helm install this time.
However the issue still persists. Unable to login to solace

kubectl logs solace-pubsubplus-0 -f
2023/06/22 04:48:24 [error] 582#582: *3 open() "/usr/sw/loads/currentload/www/login" failed (2: No such file or directory), client: 10.244.0.0, server: , request: "GET /login HTTP/1.1", host: "[IP]:32735"

**Comment by bczoma** [comment]
Hi, following works for me and I can login to the WebUI using `<service-ip-address>:8080`
```
helm install test2 solacecharts/pubsubplus --set solace.size=dev,storage.persistent=false
```
How does your way of install differ?

**Comment by ayaan604** [comment]
I really apologize I was making a silly mistake all this while...
I kept trying this url <ip:port>/login, however this url is simply incorrect, hence it was fetching 404 not found
I should've simply typed <ip:port> and it would have given me the login page automatically.

Thank you for giving your time though, I really appreciate

**Comment by bczoma** [comment]
Glad you made it work @ayaan604 , closing this then.
