### ISSUE TITLE
Pubsub+ version migration: readiness check failed

### ISSUE THREAD

**Issue by mrvivektiwari** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#132]
Need help to migrate the Pubsub+ version without any downtime and data loss.

Currently running pubsub+ with HA on EKS cluster

- pubsub+ 9.8.0.12 [Docker](https://hub.docker.com/layers/solace/solace-pubsub-standard/9.8.0.12/images/sha256-ea8705af6623eb0439006b506b586f737f449a1238f5dc952ef80f26d07b042b?context=explore)
- pubsub+ helm chart 2.1.1 [pubsubplus](https://artifacthub.io/packages/helm/solace/pubsubplus-ha/2.1.1)

**Upgrade -** 

I tried upgrading pubsub+ to the latest 10.4.1.69 but the readiness check failed and not able to do the in-place upgrade.

As soon as I updated the pubsub+ Statefulset image version to 10.4.1.69, it terminated the old monitoring pod and created a new monitoring pod with the latest version. But the new monitoring pod is not coming healthy so no backup and primary pod created. 

monitoring pod description - 

`Unhealthy  kubelet  (combined from similar events): Readiness probe failed:  INFO: readiness_check.sh-Redundancy state is not yet up.`

monitoring pod log - Running(but not healthy) -

`SYSTEM: SYSTEM_AUTHENTICATION_SESSION_OPENED: -- SEMP session :: internal authentication opened for user admin (admin)`

please suggest the best practices to migrate the pubsub+ till production without any downtime and data loss.

Didn't find any document for pubsub+  EKS migration - https://docs.solace.com/Software-Broker/SW-Broker-Upgrade/Upgrade-Selector-Current-Release.htm

**Comment by bczoma** [comment]
Hi @vivekcs0114 , it seems like you are using an older version of the Helm chart (latest is 3.3.1). If this is for a production system then fixing this needs careful analysis of your situation and environment to avoid downtime and data loss. I suggest you contact [Solace Support](https://solace.com/support) for assistance.

**Comment by bczoma** [comment]
Closing this issue now.
