### ISSUE TITLE
start_vmr.sh on Mac fails due to an error about secrets file

### ISSUE THREAD

**Issue by navneetkit** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#14]
Following is the error:
Error: secrets "killjoy-ocelot-solace-secrets" already exists

It turns out that there are 2 copies of the secret yaml file in the templates directory. The error goes away when the one ending with 'E' is deleted. 

Root cause:
The sed option –iE modifies the secrets file in place and also saves a backup file with E appended to it.
The sed command that works correctly on Mac is:
sed -Ee <exp> -i '' <file>
The  '' (empty string) will tell the command to save no backup.

**Comment by MichaelHussey** [comment]
I couldn't get this to work 

```sed_options="-E -i\"\""```

just meant that the backup file was named templates/pre-install-secret.yaml""

Instead I changed to

```
case ${os_type} in 
  "Darwin" )
    helm_type="darwin-amd64"
    sed_options="-E -i.bak"
    ;;
  "Linux" )
    helm_type="linux-amd64"
    sed_options="-i.bak"
    ;;
esac
```

And then explicitly deleted the backup file after doing the replacement.

```
rm templates/pre-install-secret.yaml.bak
```

**Comment by PhilippeKhalife** [comment]
Closing with PR#19
