### ISSUE TITLE
Should split install and start

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#15]
Current helper script pulls down all required files, modifies them then starts a Singleton or HA cluster.
This should be broken into 2 scripts:
- the first simply pulls down the environment; and
- the second does the modification and install.

Some environments such as openshift will require intermediary steps between these 2 phases.

**Comment by bczoma** [comment]
The quick start has been re-worked such that there is only a `configure.sh` script, which does the second part: modification and install. Pulling down the environment is part of the quick start procedures.

**Comment by bczoma** [comment]
This can be closed now

**Comment by KenBarr** [comment]
agree
