### ISSUE TITLE
Readyness checks unreliable.

### ISSUE THREAD

**Issue by unixunion** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#20]
The method by which readiness is determined is very confusing. The VMR needs to have a simpler way to determine readiness. 

the logs from one of my HA trio shows it is active and happy:

    Thu Feb  1 09:06:54 UTC 2018 INFO: config-sync-check.sh-Mate activity state is: "Standby"
    Thu Feb  1 09:06:54 UTC 2018 INFO: config-sync-check.sh-Redundancy is up end-to-end, Local Active Mate Standby, after 30 seconds

but the readiness probe ran earlier, and gave up. 

    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-node oridinal
    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-Current and Previous state match, not updating label
    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-Message Router is Healthy and not Active, further check required
    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-Checking if Message Router is Standby
    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-Local activity state is: "Local Inactive"
    Thu Feb  1 09:06:17 UTC 2018 WARN: readiness_check.sh-Redundancy not up or not responding, failing readiness check
    Thu Feb  1 09:06:17 UTC 2018 INFO: readiness_check.sh-Current and Previous state match, not updating label
    Thu Feb  1 09:06:17 UTC 2018 INFO: semp_query.sh-/mnt/disks/solace/semp_query.sh: count_search= ,name=admin ,password=xxx query=<rpc semp-version='soltr/8_5VMR'><show><redundancy><detail/></redundancy></show></rpc>             ,url=http://localhost:8080/SEMP ,value_search=/rpc-reply/rpc/show/redundancy/virtual-routers/primary/status/activity[text()] ,Leftovers:
    Thu Feb  1 09:06:17 UTC 2018 INFO: semp_query.sh-/mnt/disks/solace/semp_query.sh: Query passed ok
    Thu Feb  1 09:06:17 UTC 2018 INFO: semp_query.sh-/mnt/disks/solace/semp_query.sh: Value search /rpc-reply/rpc/show/redundancy/virtual-routers/primary/status/activity[text()] returned Local Inactive

This mechanism needs simplification.

**Comment by unixunion** [comment]
I have tried deferring the readiness check by a minute, but it just never actually executes then. So I have for the mean time removed it entirely, and am using httpGet instead with good success.

        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 5
          httpGet:
            path: /health-check/guaranteed-active
            port: 5550
            scheme: HTTP


Failover and back works fine, though I don't really know how the lighthouse mechanism is impacted.

**Comment by KenBarr** [comment]
In your initial report, it looks like you are showing logs from the primary VMR and it is returning "Local Inactive",  this is not completely  active and happy.
It would be great if you could provide the output of "show redundancy detail" when the VMR is in this state.  It is not obvious to me the healthcheck is doing anything wrong.

In your follow-on
Simplifying the healthcheck like this will not work. 
Without label manipulation the load-balancer will not follow the Solace HA Active message router.

**Comment by unixunion** [comment]
I have changed the selector to exclude the active boolean, and it actually does work. Provided that the healtcheck to /health-check/guaranteed-active will always be correct.

screencast: https://vimeo.com/253785448

**Comment by KenBarr** [comment]
I do not believe it is working like you think.  What is happening is that the loadbalancer is trying all the VMRs in round-robin.  It will fail fast on the non-active VMRs and then succeed on the active.  The Solace SDK is doing re-tries on the failed connections and masking this issue for you.  If you try and do something like ssh to that address you should see every 3rd ssh succeed.

**Comment by unixunion** [comment]
The K8s loadbalancer won't RR on non-ready instances. see same MAC for all SSH attempts:

root@testbox-0:/pubSubTools# ssh solace 22
The authenticity of host 'solace (100.70.162.95)' can't be established.
ECDSA key fingerprint is 8f:02:c1:81:ef:2e:08:f5:a6:de:dc:40:5d:fe:ef:45.
Are you sure you want to continue connecting (yes/no)? ^C
root@testbox-0:/pubSubTools# ssh solace 22
The authenticity of host 'solace (100.70.162.95)' can't be established.
ECDSA key fingerprint is 8f:02:c1:81:ef:2e:08:f5:a6:de:dc:40:5d:fe:ef:45.
Are you sure you want to continue connecting (yes/no)? ^C
root@testbox-0:/pubSubTools# ssh solace 22
The authenticity of host 'solace (100.70.162.95)' can't be established.
ECDSA key fingerprint is 8f:02:c1:81:ef:2e:08:f5:a6:de:dc:40:5d:fe:ef:45.
Are you sure you want to continue connecting (yes/no)? ^C
root@testbox-0:/pubSubTools# ssh solace 22
The authenticity of host 'solace (100.70.162.95)' can't be established.
ECDSA key fingerprint is 8f:02:c1:81:ef:2e:08:f5:a6:de:dc:40:5d:fe:ef:45.

Also see the Endpoint is clearly aware of which node is serviceable

Name:         solace
Namespace:    default
Labels:       app=solace
              chart=solace-0.2.0
              heritage=Tiller
              release=musty-mastiff
Annotations:  <none>
Subsets:
  Addresses:          100.121.51.12
  NotReadyAddresses:  100.109.177.207,100.124.246.143
  Ports:
    Name  Port   Protocol
    ----  ----   --------
    smf   55555  TCP
    ssh   22     TCP
    semp  8080   TCP

Events:  <none>

**Comment by KenBarr** [comment]
arg,  Yes of course you are correct loadbalancer will work.  What will not work for you is rolling upgrades.  The pods need to be in ready state to upgrade.   An upgrade will stall on the monitor node.

**Comment by unixunion** [comment]
Ok, noted. I wonder fi I could blow away the non-ready instances, deploy the updated version, then blow away the active.

**Comment by KenBarr** [comment]
yes,  remove from solaceStatefulset.yaml   
updateStrategy: 
    type: RollingUpdate

Then you fall back to on-delete upgrades.  Delete each node one at a time and do not delete the next node until the recovered on is redundancy: up.  If you have 2 nodes not in redundancy: up there will be a stoppage in traffic.

Or. we can figure out what went wrong with the redundancy check.

**Comment by unixunion** [comment]
Yep, I will fork and try make a reproducer, though my issue could be my environment specific. k8s on AWS using "ClusterIP" loadbalancer type instead of the default ELB.

**Comment by unixunion** [comment]
Ok I have re-deployed, i've only changed the type of loadbalancer to "ClusterIP".  and this is the example persistent HA: small-persist-ha-provisionPvc.yaml

    incindiary-sloth-solace-0> show redundancy detail
    Configuration Status     : Enabled
    Redundancy Status        : Up
      Last Failure Reason    : Message spools out of sync
      Last Failure Time      : Feb  1 2018 14:19:34 UTC
    Operating Mode           : Message Routing Node
    Switchover Mechanism     : Hostlist
    Auto Revert              : No
    Redundancy Mode          : Active/Standby
    Active-Standby Role      : Primary
    Mate Router Name         : incindiaryslothsolace1
      Connect Via Addr       : incindiary-sloth-solace-1.incindiary-sloth-solace-
                             :   discovery.default.svc:8741
    ADB Link To Mate         : Up
      Last Failure Reason    : Mate Link Restart
      Last Failure Time      : Feb  1 2018 14:18:45 UTC
    ADB Hello To Mate        : Up
      Last Failure Reason    : N/A
      Last Failure Time      :
      Hello Interval (ms)    : 1000
      Hello Timeout (ms)     : 3000
      Avg Hello Latency (ms) : 1
      Max Hello Latency (ms) : 27
    
                                   Primary Virtual Router  Backup Virtual Router
                                   ----------------------  ----------------------
    Activity Status                Local Active            Shutdown
    Routing Interface              intf0:1                 intf0:1
    Routing Interface Status       Up
    VRRP Status                    Initialize
    VRRP Priority                  250
    Message Spool Status           AD-Active
    
    Priority Reported By Mate:     Standby
      ADB Hello Protocol             Standby
      VRRP                           Standby (100)
    
    Activity Status:               Local Active
      Operational Status             Ready
        Redundancy Config Status       Enabled
        Message Spool Status           Ready
      SMRP Status                    Ready
        Db Build Status                Ready
        Db Sync Status                 Ready
      Internal Priority              Active
      Internal Activity Status       Local Active
      Internal Redundancy State      Pri-Active
    
    Message Spool Status:          Ready
      Message Spool Config Status    Enabled
      VRID Config Status             Ready
      ADB Status                     Ready
        Flash Module Status            Ready
        Power Module Status            Ready
      ADB Contents                   Ready
        Local Contents Key             213.203.134.188:2,1
        Mate Contents Key              213.203.134.188:2,1
        Schema Match                   Yes
      Disk Status                    Ready
      Disk Contents                  Ready
        Disk Key (Primary)             213.203.134.188:2,1
        Disk Key (Backup)              213.203.134.188:2,1
      ADB Datapath Status            Ready
      Internal Redundancy State      AD-Active
      Lock Owner                     N/A
    
    VRID Config Parameter          Local Configuration     Received From Mate
    -----------------------------  ----------------------  ----------------------
      Primary VRID                   213.203.134.188         213.203.134.188
      Backup VRID
      AD-Enabled VRID                213.203.134.188         213.203.134.188
    
      Disk WWN:
        Local:              N/A
        Received From Mate: N/A
      * - indicates configuration mismatch between local and mate router
    
    incindiary-sloth-solace-0>

**Comment by KenBarr** [comment]
Tried a couple of times to re-produce this issue in AWS and do not see it happening.  Is this 100% reproducible for you?

**Comment by unixunion** [comment]
Yes, 100%. Have you tried changing LB to ClusterIP? Otherwise maybe its something in how our k8s is deployed via Kops. Let me know id you want to setup a call and I can do a screen share and hopefully we can find the root cause of this.

**Comment by unixunion** [comment]
Thanks for the call, root cause identified as no permission to edit pod. 

    [root@precise-owl-solace-0 ~]# rm /tmp/activity_state  && /mnt/disks/solace/readiness_check.sh 7
    rm /tmp/activity_state  && /mnt/disks/solace/readiness_check.sh 7
    rm: remove regular file ‘/tmp/activity_state’? y
    State file not found, creating!
    Fri Feb  2 13:36:49 UTC 2018 INFO: readiness_check.sh-node oridinal
    Fri Feb  2 13:36:49 UTC 2018 INFO: readiness_check.sh-Message Router is Active and Healthy
    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {
  
      },
      "status": "Failure",
      "message": "pods \"precise-owl-solace-0\" is forbidden: User \"system:serviceaccount:default:default\" cannot patch pods in the namespace \"default\"",
      "reason": "Forbidden",
      "details": {
        "name": "precise-owl-solace-0",
        "kind": "pods"
      },
      "code": 403
    }

**Comment by unixunion** [comment]
The relevant binding + role to correct this for RBAC enabled Kubernetes:

    kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: pod-tag-updater
    rules:
    - apiGroups: [""] # "" indicates the core API group
      resources: ["pods"]
      verbs: ["patch"]
    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: solace
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: pod-tag-updater
    subjects:
    - kind: Group
      name: system:serviceaccounts
      apiGroup: rbac.authorization.k8s.io

**Comment by KenBarr** [comment]
Thanks for the detailed binding and role.  
Will test and let you know when we have fix incorporated.

**Comment by KenBarr** [comment]
I feel we should close this issue.  The root cause was pod permissions not that the scripts where in-reliable.

**Comment by PhilippeKhalife** [comment]
Fixed with latest PR.
