### ISSUE TITLE
start_vmr script has bad template reference for secrets

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#22]
This line:
sed ${sed_options} "s/SOLOS_ADMIN_PASSWORD/${solace_password}/g" templates/pre-install-secret.yaml
should read:
sed ${sed_options} "s/SOLOS_ADMIN_PASSWORD/${solace_password}/g" templates/secret.yaml

We are not doing pre-install helm step but instead relying on template dependencies to get order correct.

**Comment by KenBarr** [comment]
Also next line rm reference is wrong  rm templates/pre-install-secret.yaml.bak should be  rm templates/secret.yaml.bak

**Comment by PhilippeKhalife** [comment]
Fixed with latest.
