### ISSUE TITLE
templates/pre-install-secret.yaml not present

### ISSUE THREAD

**Issue by Derrick-Hodges** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#34]
Hi

The start_vmr.sh script references a template called templates/pre-install-secret.yaml. This file isn't present in the templates directory.

**Comment by wlyeow** [comment]
Please do a `git pull`. This is already addressed in f8b2e6b.

**Comment by bczoma** [comment]
It seems this can be closed now.
