### ISSUE TITLE
Running the configure script twice doesn't work

### ISSUE THREAD

**Issue by dickeyf** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#54]
I ran configure.sh once, forgot to set the admin password.  The script will default to "", which is a value that'll make the deployment invalid.  The VMR crashes (And hard to understand why) as a direct result of that.

I ran it a second time, but it had to effect.

Recommendations:
The script should fail if no password is specified to avoid users getting into the same issue.
The script should replace templates/secret.yaml with an original, otherwise the SOLOS_ADMIN_PASSWORD token won't be there, and sed will do nothing.

Probably should do the same with any other files which has sed TOKENs in it.

**Comment by bczoma** [comment]
This is now resolved by PR#53, ready to be closed.
