### ISSUE TITLE
How to pass different args to pods in StatefulSets

### ISSUE THREAD

**Issue by TracyWJ** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#62]
I can deploy the ha demo "prod1k-persist-ha-provisionPvc.yaml" but the 3 pods are created with the same cpu and memory configuration (request and limits). I'd like to set different args (CPU & Memory) for the monitor pod as the customer required. So how can I pass different args to pods in StatefulSets template? Can I based on their ordinal index?

**Comment by bczoma** [comment]
In this current version using StatefulSets, all HA nodes are treated the same so this is unfortunately not possible. It is a known limitation and a planned feature

**Comment by TracyWJ** [comment]
Got it, thank you.
