### ISSUE TITLE
Version 1.16 of Kubernetes has moved StatefulSets and RBAC out of v1beta

### ISSUE THREAD

**Issue by davesargrad** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#66]
The Solace Helm Chart fails with 1.16 of K&S. It worked with 1.13.

The failure:
[root@tonga solace]# helm install . -f values.yaml
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"

The reason for this is seen in the 1.16 documentation

![image](https://user-images.githubusercontent.com/48793689/67417443-c590a000-f596-11e9-943f-938c88580978.png)

**Comment by bczoma** [comment]
Thanks for raising Dave, will include a fix in the next update.

**Comment by davesargrad** [comment]
I appreciate your fast response.. Ty Sir.

**Comment by davesargrad** [comment]
@bczoma Could you please tell me about how long it will take for a bug fix to be available? Is this something that will take hours, days, or weeks? 

Knowing your thought on this will help me to understand how to approach this problem. If its hours or days, then I'll simply wait for the fix.


Thanks

**Comment by bczoma** [comment]
Looks like a simple fix that can be done in the next day or so. I'll update if not.

**Comment by bczoma** [comment]
@davesargrad , I have made the fixes but takes a bit of time to get through our internal verification.

In the meantime, here are the fixes that worked for me and you can apply the diffs to get going as well:
```
----------------------- solace/templates/podModRbac.yaml -----------------------
 kind: ClusterRoleBinding
-apiVersion: rbac.authorization.k8s.io/v1beta1
+apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: {{ template "solace.fullname" . }}-serviceaccounts-to-podtagupdater
 roleRef:

------------------- solace/templates/solaceStatefulSet.yaml -------------------
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    app: {{ template "solace.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
+  selector:
+    matchLabels:
+      app: {{ template "solace.name" . }}
+      release: {{ .Release.Name }}
   serviceName: {{ template "solace.fullname" . }}-discovery
   replicas: {{- if .Values.solace.redundancy }} 3 {{- else }} 1 {{- end }}
 {{- if semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion }}
```

**Comment by davesargrad** [comment]
Thanks Much. I will apply the fixes. I appreciate your fast response. Goes a long way.

**Comment by davesargrad** [comment]
I was able to get solace deployed with your fixes. :)

**Comment by bczoma** [comment]
This has issue has been addressed as https://github.com/SolaceProducts/solace-kubernetes-quickstart/pull/67 and can be closed
