### ISSUE TITLE
Failed to Run Solace on Kubernetes Cluster that Uses CEPH-RBD Provisioner

### ISSUE THREAD

**Issue by davesargrad** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#69]
We've been using the Solace Helm Chart successfully using NFS storage. However this is not the storage we wish to use. I have successfully setup a CEPH cluster. I've successfully configured the RBD provisioner to automatically create the PV requested by the Solace Pods PVC, and the RBD Provisioner successfully creates the CEPH PV. However the Solace Pod fails to attach to the storage. It shows an error that suggests that the "rbd" executable is not available in the Solace Pod.

In the following we see the "kissable-panda pod" created using the Solace Helm Chart and the CEPH "fast-rbd" storage class. We also see the successfully bound PVC for this solace pod.
![image](https://user-images.githubusercontent.com/48793689/68866563-9d422000-06c2-11ea-9a24-6d744dc298d9.png)

However the pod itself fails to attach as we see here:
![image](https://user-images.githubusercontent.com/48793689/68867188-69b3c580-06c3-11ea-852b-0b72431eaee0.png)

I've googled the error 

> fail to check rbd image status with (executable file not found in $path)

and I've found several links such as the 
[following](https://github.com/kubernetes-incubator/external-storage/issues/1002)

This seems to suggest that the rbd binary is not found in the container image.

Thoughts on resolving this?

Thanks.
Dave

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/68868361-68839800-06c5-11ea-9508-ce88ace4bc30.png)

**Comment by davesargrad** [comment]
I think I may have found my problem. My use of CEPH RBD seems to be at the core of the problem.

According to this documentation:
https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/

I may have an approach... I'll follow up

**Comment by bczoma** [comment]
This would be great Dave, as we haven't had a use case to test the deployment using CEPH RBD yet. If you overcome the immediate issue but then get similar logs as with NFS indicating slow storage/latency then also try to set the `storage.nfs` flag in values.

**Comment by davesargrad** [comment]
I got past this issue. It was simply a package (ceph-common) missing from the K8S cluster that caused the volume to fail to attach.

The end result is I now have solace up and running with a proper CEPH RBD storage framework.

**Comment by bczoma** [comment]
Thanks Dave, good to know CEPH RBD works. Assuming this issue can be closed.

**Comment by davesargrad** [comment]
Yes Sir. As usual  i always appreciate your response. Ty
