### ISSUE TITLE
Extending basic example to support Horizontal Scaling

### ISSUE THREAD

**Issue by RnD-John** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#70]
**Basic question:**
Can you provide an example .yaml file that explicitly assigns the designated (by a red arrow) ports?
![image](https://user-images.githubusercontent.com/57505178/68878839-637b1480-06d6-11ea-9aab-8dbced00f89d.png)

**Background:**
I am trying to setup a 3 node cluster using the horizontal scaling configuration described here:
https://docs.solace.com/Configuring-and-Managing/DMR-Examples-Scaling.htm#Step2

To do this for the configuration above, step 2 is modified to reflect my service ports.
connect-via 192.0.2.1 => connect-via  myDomain.com:31891
connect-via 192.0.2.2 => connect-via  myDomain.com:32558
connect-via 192.0.2.3 => connect-via  myDomain.com:31258

NOTE: I am using the 55555 port mapping because I also comment out the transport SSL line in my basic test.

The procedure I have properly establishes the 3 node cluster and works perfectly well until one of the members of the cluster fails. Upon re-instantiating the member, its port changes requiring all peers to have to modify the port mappings of their internal links. Ideally, I'd like to specify the ports to use at creation so that when a member comes back online it can easily drop into place with minimal impact.

Please advise.

Thank you,
-John

**Comment by bczoma** [comment]
Hi John, can you try to specify ClusterIP addresses: `solace1-solace.default.svc.cluster.local:55555`, etc. ?
These should dynamically resolve to the always active pod.

**Comment by RnD-John** [comment]
Using the ClusterIP addresses as suggested works. I was able to establish the initial cluster as well as delete, purge, and restore the second broker without touching the first or third broker.
Thank you for the prompt response.

-John

**Comment by bczoma** [comment]
Nice, I'll ensure it is covered in the quickstart documentation.
Regards: Balazs
