### ISSUE TITLE
Readiness Probe Fails on Backup Broker in HA Pair due to nonHA Message Spool.

### ISSUE THREAD

**Issue by RnD-John** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#72]
I have successfully setup a 3 node HA group on the k8 using this guide:
https://docs.solace.com/Configuring-and-Managing/Configuring-HA-Groups.htm

Everything works as expected including the "Validate Failover" step.

Under this configuration, kubectl get pods reports the backup broker as not ready:
![image](https://user-images.githubusercontent.com/57505178/70070570-d97de780-15c1-11ea-9f53-f6fdf1f5509c.png)

This is unexpected because it seems to properly take over when the primary broker releases activity to it. The only reported issues are warnings referring to the nonHA message spool. Failing the readiness check due to nonHA related warnings is not expected.

Describing the seemingly functional backup broker yields:
`]# kubectl describe pod solace2-solace-0
Name:         solace2-solace-0
Namespace:    default
Priority:     0
Node:         <myDomain>/<myIP>
Start Time:   Mon, 02 Dec 2019 13:58:45 -0500
Labels:       active=false
              app=solace
              controller-revision-hash=solace2-solace-7855574578
              release=solace2
              statefulset.kubernetes.io/pod-name=solace2-solace-0
Annotations:  <none>
Status:       Running
IP:           10.244.1.81
IPs:
  IP:           10.244.1.81
Controlled By:  StatefulSet/solace2-solace
Containers:
  solace:
    Container ID:  docker://ec51c6517fee9d76d50f738e9537c82e7415727b5a93e422e99c6be24d9a6aee
    Image:         solace/solace-pubsub-standard:latest
    Image ID:      docker-pullable://solace/solace-pubsub-standard@sha256:57c2b6c4d5ce3c0166f13efa3857ebdc3353d462a5be4974db9b7c44662c73a9
    Ports:         2222/TCP, 8080/TCP, 55555/TCP, 55003/TCP, 55443/TCP, 60943/TCP, 60080/TCP, 60443/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      bash
      -ec
      source /mnt/disks/solace/init.sh
      # not using postinstall hooks because of order dependencies
      # launch config check then Solace so VCMR can provide return code
      nohup /mnt/disks/solace/config-sync-check.sh &
      /usr/sbin/boot.sh

    State:          Running
      Started:      Tue, 03 Dec 2019 10:50:06 -0500
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Dec 2019 13:59:31 -0500
      Finished:     Tue, 03 Dec 2019 10:50:05 -0500
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     2
      memory:  7680Mi
    Requests:
      cpu:      1200m
      memory:   4Gi
    Liveness:   tcp-socket :8080 delay=300s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [/mnt/disks/solace/readiness_check.sh] delay=30s timeout=1s period=5s #success=1 #failure=3
    Environment:
      STATEFULSET_NAME:       solace2-solace
      STATEFULSET_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /dev/shm from dshm (rw)
      /mnt/disks/secrets from secrets (ro)
      /mnt/disks/solace from config-map (rw)
      /usr/sw/adb from data (rw,path="adb")
      /usr/sw/internalSpool from data (rw,path="internalSpool")
      /usr/sw/internalSpool/softAdb from data (rw,path="softAdb")
      /usr/sw/jail from data (rw,path="jail")
      /usr/sw/var from data (rw,path="var")
      /var/lib/solace/diags from data (rw,path="diags")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-22scj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-solace2-solace-0
    ReadOnly:   false
  config-map:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      solace2-solace
    Optional:  false
  secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  solace2-solace-secrets
    Optional:    false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  default-token-22scj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-22scj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                      From                            Message
  ----     ------     ----                     ----                            -------
  Warning  Unhealthy  34m                      kubelet, <myDomain>  Readiness probe failed: Tue Dec  3 16:07:01 UTC 2019 INFO: readiness_check.sh-nonHA Message Router message spool is down
  Warning  Unhealthy  34m                      kubelet, <myDomain>  Readiness probe failed: Tue Dec  3 16:07:06 UTC 2019 INFO: readiness_check.sh-nonHA Message Router message spool is down
  Warning  Unhealthy  2m29s (x15258 over 21h)  kubelet, <myDomain>  (combined from similar events): Readiness probe failed: Tue Dec  3 16:39:21 UTC 2019 INFO: readiness_check.sh-nonHA Message Router message spool is down
`

**Comment by bczoma** [comment]
Hi John, there may be multiple reasons as setting up a redundant configuration requires quite a few steps.
The suggested way is to not go through all the manual steps of setting up three PubSub+ deployments and configure them to create a working HA deployment. 
You can set `solace.redundancy` to `true` in the solace/values.yaml file and then run the `helm install` command. This will use automation to set up redundancy and config-sync. This also makes use of kubernetes-local DNS resolvable hostnames to refer to the Solace nodes instead of IP addresses that would change when a pod goes down or gets evicted.

**Comment by RnD-John** [comment]
Ah yes. Using solace.redundancy to establish the HA cluster is a lot easier.

Are there additional commands to force the members of the cluster to use 3 different tainted nodes?

Thank you for the guidance,

-John

**Comment by KenBarr** [comment]
We currently allow kubernetes full control on placing pods on nodes.  We do not use taints, node affinity or anti-affinity.   It will likely be difficult to advise a scheme that would satisfy all requirements in all environments.  

I think an anti-affinity to drive toward spread placement might be the simplest if you are going to allow Solace to be deployed on all nodes.  

We are ok with multiple Solace pods on a node, just not multiple Solace containers in a pod.

**Comment by RnD-John** [comment]
My envisioned schema would potentially deploy the HA group across multiple data-centers to establish geographic diversity. I will look into an anti-affinity approach as you suggest.

Thank you,

**Comment by KenBarr** [comment]
We have drifted from product issue to solution architecture and git issues is not the correct form for this discussion.  I would suggest solace community. https://solace.community/ if you do not have a support account.  
But generally speaking the disaster recovery feature is a better fit then trying to build a stretch cluster on Solace.   The main problem is where to place the monitor node.  Keep in mind two nodes must be able to communicate at all times for cluster to stay up.

**Comment by RnD-John** [comment]
Ok, thank you for your guidance. I will close this issue and move any further discussion to the solace.community.
