### ISSUE TITLE
Broken Link in docs/PubSubPlusK8SDeployment.md

### ISSUE THREAD

**Issue by kewei5zhang** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#87]
Broken link in [docs/PubSubPlusK8SDeployment.md](https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/master/docs/PubSubPlusK8SDeployment.md)

[PubSub+ Event Broker on Google Kubernetes Engine (GKE) quickstart](https://github.com/SolaceProducts/solace-gke-quickstart/tree/9.4Release#how-to-deploy-a-solace-pubsub-software-event-broker-onto-gke).

**Comment by bczoma** [comment]
This can be closed
