### ISSUE TITLE
NOTES.txt has a bad substring causing the templates to not render

### ISSUE THREAD

**Issue by sushil-rxr** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#94]
The NOTES.txt has an entry such as "The requested connection scaling tier for this deployment is: max {{ substr 4 10 .Values.solace.size }} connections." This substring logic is failing when we use the strings such as prod1k etc. for the solace.size parameter value.

**Comment by bczoma** [comment]
Hi sushil-rxr, thanks for raising I'll look into this for the next update

**Comment by bczoma** [comment]
Hi, I have just tried with `solace.size=prod1k` and getting:
```
== Performance and resource requirements ==
The requested connection scaling tier for this deployment is: max 1k connections.
```
Wondering if you are getting the same and if so what the issue with above is.

**Comment by bczoma** [comment]
@sushil-rxr  - kindly provide an update if this is still an issue
