### ISSUE TITLE
Broken link to helm charts in README.md

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#98]
**Link here:**

In this quick start we go through the steps to set up a PubSub+ Software Event Broker using [Solace PubSub+ Helm charts](//hub.helm.sh/charts/solace).

**Suggestion:**

In this quick start we go through the steps to set up a PubSub+ Software Event Broker using [Solace PubSub+ Helm charts](//artifacthub.io/packages/search?&repo=solace).

**Comment by bczoma** [comment]
Thank you for reporting. Fixed, will be published at the next update.
