### ISSUE TITLE
Enhancement: Add New Helm Chart Parameter for Broker Message Spool Limit

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#99]
**What** 
Add a new helm chart parameter to configure the max spool usage limit on deployment of the brokers

**Why**
Presently, a chart parameter of `storage.size` is available to control the size of the persistent volume claim for each broker pod. 
It can be assumed that a user will specify a value to override the default to support larger message spools with the larger volume.

There is not however any means to control the broker's configured `max spool usage` limit as part of deploying the stateful set. Currently this is defaulting to 1500MB and needs config to be subsequently issued following broker creation to increase it.

**How**
There is already a container startup [config key](https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Configuration-Keys-Reference.htm) available to manage this, requesting the addition of a new helm chart parameter `solace.maxspoolusage` that allows a value other than the 1500MB default to be collected.

The collected value can then be exported as an environment variable in the file [solaceConfigMap.yaml](../blob/master/pubsubplus/templates/solaceConfigMap.yaml) alongside the existing config keys such as  `export system_scaling_maxconnectioncount`.

**Impact Assessment**
A new optional parameter that _only when present_ can export the appropriate config key. If not present then nothing is exported and the broker level defaults, or user issued config change, continue to apply for existing chart deployments that may execute an upgrade.

**Comment by dwongkm** [comment]
thanks, Jamil.  I have created an entry in JIRA to keep track of this request.  

Douglas

**Comment by bczoma** [comment]
In the short term `export system_scaling_maxqueuemessagecount` can be manually added to https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/master/pubsubplus/templates/solaceConfigMap.yaml#L19 but care must be taken to also update https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/blob/master/pubsubplus/templates/solaceStatefulSet.yaml#L46-L84 if required, consulting the [Solace documentation for Additional System Resources](https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/System-Scaling-Parameters.htm#max-messages-containers).
A longer term solution will be devised to make this automated.

**Comment by itsJamilAhmed** [comment]
With the config key called `messagespool/maxspoolusage` being the one of interest here to configure the spool size on broker startup, is this change not exclusive to just the file [solaceConfigMap.yaml](../blob/master/pubsubplus/templates/solaceConfigMap.yaml)? That's where all the other config keys get exported. 

Am I missing something or should this change not be along the lines of adding:

```
{{- if eq .Values.solace.maxspoolusage }}
    export messagespool_maxspoolusage="{{.Values.solace.maxspoolusage}}"
```

after line 18 of [solaceConfigMap.yaml](../blob/master/pubsubplus/templates/solaceConfigMap.yaml#L18) 

The key you reference in your comment (`system_scaling_maxconnectioncount`) is already handled no?

**Comment by bczoma** [comment]
@itsJamilAhmed You're right, `system_scaling_maxqueuemessagecount` is the one I thought and updated my original comment with.
But it seems you are only interested in `messagespool/maxspoolusage` ?

**Comment by itsJamilAhmed** [comment]
Yep, just a parameter to modify the message spool limit in MB is all I'm after with this particular request. 

With the `system/scaling/maxqueuemessagecount` defaulting at 100 million messages, it's more than enough that I'm fine without something for that. 😊

**Comment by bczoma** [comment]
Sounds good, will add it to the next rev

**Comment by bczoma** [comment]
https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart/pull/109 has added support to provide any additional env variable to the PubSub+ container, which can also be used for config key.
Future update will add specific support to all supported scaling parameters.
